<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CircuitSimulator.Core\CircuitSimulator.Core.csproj" />
    <ProjectReference Include="..\CircuitSimulator.Editor.Contracts\CircuitSimulator.Editor.Contracts.csproj" />
  </ItemGroup>

</Project>
